name: Creative
main: NamelessLeaf\Creative\Main
author: NamelessLeaf
version: "2.0"
description: "A Plugin"
api: 3.17.2
commands:
 playcreative:
  description: "Open Creative UI"
  permission: use.creativeui
