name: Creative
aurthor: NamelessLeaf
version: 1.0
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11]
main: NamelessLeaf\Creative\Main

commands:
 playcreative:
  description: "Open Creative UI"
  permission: use.creativeui
